base_config: shared_ap
scene_name: shared_ap
viz_scene_path: "/home/hieule/research/marlis2/default_scenes/blender/shared_ap/shared_ap.xml"
compute_scene_path: "/home/hieule/research/marlis2/default_scenes/blender/shared_ap/shared_ap.xml"
tile_path: "/home/hieule/research/marlis2/default_scenes/blender/tile/tile.obj"
resolution: [1920, 1080]
rm_vmin: -120
rm_vmax: -60
verbose: true
cam_position: [0.0, 2.1, 55.0]
cam_orientation: [0.0, 0.0, 0.0]
cam_look_at: [0.0, 2.2, 0.0]
frequency: 60e9
synthetic_array: true

# Reflector parameters
rt_positions: [[7.4, 9.5, 2.86059], [-7.4, 9.5, 2.86059]]

# Transmitter and receiver parameters
tx_num_rows: 1
tx_num_cols: 2
tx_vertical_spacing: 0.5
tx_horizontal_spacing: 0.5
tx_pattern: tr38901
tx_polarization: V
tx_positions: [[0.0, 10.0, 3.8], [0.0, 10.0, 3.8]]
tx_orientations: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]
rx_num_rows: 1
rx_num_cols: 1
rx_vertical_spacing: 0.5
rx_horizontal_spacing: 0.5
rx_pattern: iso
rx_polarization: V
rx_positions:
    [[4.0, 0.0, 1.5], [-4.0, 0.0, 1.5], [0.0, 3.0, 1.5], [0.0, -3.0, 1.5]]
rx_orientations:
    [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]

# Path tracing parameters
rm_max_depth: 10
rm_cell_size: [0.5, 0.5]
rm_num_samples: 1e6
path_max_depth: 8
path_num_samples: 1e6
diffuse_reflection: true
