base_config: data_center
scene_name: data_center

blender_app: "/home/hieule/blender/blender-3.3.14-linux-x64/blender"
blender_dir: "/home/hieule/blender/"
xml_dir: "/home/hieule/research/rs/local_assets/blender"
blender_script: "/home/hieule/research/rs/rs/bscripts/generate_data_center.py"
image_dir: "/home/hieule/research/rs/local_assets/images"

resolution: [1920, 1080]
rm_vmin: -80
rm_vmax: -30
verbose: true
cam_position: [0.0, 0.5, 40.0]
cam_orientation: [0.0, 0.0, 0.0]
cam_look_at: [0.0, 0.55, 0.0]
frequency: 60e9
synthetic_array: true

# Reflector parameters
rf_positions: [[5.7, 0.0, 2.9], [-5.7, 0.0, 2.9]]

# Transmitter and receiver parameters
tx_num_rows: 1
tx_num_cols: 2
tx_vertical_spacing: 0.5
tx_horizontal_spacing: 0.5
tx_pattern: tr38901
tx_polarization: V
tx_positions: [[0.0, 0.0, 3.8], [0.0, 0.0, 3.8]]
tx_orientations: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]
rx_num_rows: 1
rx_num_cols: 1
rx_vertical_spacing: 0.5
rx_horizontal_spacing: 0.5
rx_pattern: iso
rx_polarization: V

rx_positions: [[4.0, 0.0, 1.5], [-4.0, 0.0, 1.5]]
rx_orientations: [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]

# Path tracing parameters
rm_max_depth: 8
rm_cell_size: [0.2, 0.2]
rm_num_samples: 1e6
# rm_stop_threshold: -90.0
rm_diffuse_reflection: True
rm_rr_depth: -1
path_max_depth: 8
path_num_samples: 1e6
